exec-once = /nix/store/rxzvps8zldnz4sgphbw6893n6ikai6gn-dbus-1.14.10/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
$browser=vivaldi
$filemanager=thunar
$menu=vicinae
$mod=SUPER
$modShift=SUPER_SHIFT
$windowMod=ALT
$windowModShift=ALT_SHIFT
$terminal=wezterm
animations {
  bezier=easeOutQuint,0.23,1,0.32,1
  bezier=easeInOutCubic,0.65,0.05,0.36,1
  bezier=linear,0,0,1,1
  bezier=almostLinear,0.5,0.5,0.75,1.0
  bezier=quick,0.15,0,1,1
  animation=global, 1, 10, default
  animation=border, 1, 5.39, easeOutQuint
  animation=windows, 1, 4.79, easeOutQuint
  animation=windowsIn, 1, 4.1, easeOutQuint, popin 87%
  animation=windowsOut, 1, 1.49, linear, popin 87%
  animation=fadeIn, 1, 1.73, almostLinear
  animation=fadeOut, 1, 1.46, almostLinear
  animation=fade, 1, 3.03, quick
  animation=layers, 1, 3.81, easeOutQuint
  animation=layersIn, 1, 4, easeOutQuint, fade
  animation=layersOut, 1, 1.5, linear, fade
  animation=fadeLayersIn, 1, 1.79, almostLinear
  animation=fadeLayersOut, 1, 1.39, almostLinear
  animation=workspaces, 1, 1.94, almostLinear, fade
  animation=workspacesIn, 1, 1.21, almostLinear, fade
  animation=workspacesOut, 1, 1.94, almostLinear, fade
  enabled=yes, please :)
}

general {
  gaps_in=2
  gaps_out=2
}

monitorv2 {
  output=eDP-1
  mode=1920x1080@60
  position=auto
}

monitorv2 {
  output=HDMI-A-2
  mode=1920x1080@60
  position=auto-center-left
}

bind=$mod, T, exec, $terminal
bind=$mod, E, exec, $filemanager
bind=$mod, SPACE, exec, $menu toggle
bind=$mod, B, exec, $browser
bind=$mod, Q, killactive,
bind=$mod, M, exit,
bind=$mod, P, pseudo,
bind=$mod, T, togglesplit,
bind=$mod, S, togglegroup,
bind=$mod, l, movefocus, r
bind=$mod, k, movefocus, d
bind=$mod, j, movefocus, u
bind=$mod, h, movefocus, l
bind=$mod, right, movefocus, r
bind=$mod, up, movefocus, u
bind=$mod, down, movefocus, d
bind=$mod, left, movefocus, l
bind=$modShift, l, movewindow, r

bind=$windowMod, 1, workspace, 1
bind=$windowMod, 2, workspace, 2

binde= , xf86audioraisevolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05+ 
binde= , xf86audiolowervolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05-

exec-once=waybar
exec-once=dunst
exec-once=vicinae server
exec-once=blueman-applet

gesture=3, horizontal, workspace
windowrule=float on, match:class floating-applet
